### ISSUE TITLE
Loading error (-102).

### ISSUE THREAD

**Issue by sureshsp** [scoumbourdis/grocery-crud-databases#5]
I tried to connect with sql. And i followed your instruction clearly. But i Faced Loading error (-102).Please help me to solve.

**Comment by scoumbourdis** [comment]
Hello @sureshsp ,

SQL database is not available as implementation. You can see that the model extension is empty: https://github.com/scoumbourdis/grocery-crud-databases/blob/master/application/models/grocery_crud_model_mssql.php

If you would like to connect with MSSQL I would suggest to use Grocery CRUD Enterprise (https://www.grocerycrud.com/enterprise)

Regards
Johnny
