### ISSUE TITLE
Connecting to heroku with postgress

### ISSUE THREAD

**Issue by Turtugilla** [scoumbourdis/grocery-crud-databases#6]
Im setting the  database.php but im getting this error 
![image](https://user-images.githubusercontent.com/38962557/48678947-bcf64500-eb4f-11e8-9674-90454a74aa8b.png)

.. do you know what the dbdriver is for postgresql?
	'dbdriver' => ', ????????????

**Comment by scoumbourdis** [comment]
Hello @Turtugilla,

It seems that there is not any contribution for Postgres database for Grocery CRUD Community edition. I did create this repo so people that did change the model will share publicly their code. In case you are interested about Grocery CRUD and Postgres connection you should go with: Grocery CRUD Enterprise (https://www.grocerycrud.com/enterprise) that supports Postgres database

Regards
Johnny
